# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1
Make an array a of size 6 × 4 where every element is a 2.

In [ ]:
import numpy as np
a = np.ones((6,4))*2
print(a)

## Exercise 2
Make an array b of size 6 × 4 that has 3 on the leading diagonal and 1
everywhere else. (You can do this without loops.)

In [2]:
b = np.ones((6,4))
b[range(4), range(4)] = 3
print(b)

[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercise 3
Can you multiply these two matrices together? Why does a * b work, but
not dot(a,b)?

In [4]:
print(a * b)
np.dot(a, b)
#dot function uses dot multiplication of matricies, so the dimentions of the two matricies must be inverse of each other

[[6. 2. 2. 2.]
 [2. 6. 2. 2.]
 [2. 2. 6. 2.]
 [2. 2. 2. 6.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

## Exercise 4
Compute dot(a.transpose(),b) and dot(a,b.transpose()). Why are
the results different shapes?

In [5]:
print("np.dot(a.transpose(),b)\n", np.dot(a.transpose(),b), "\n")
print("np.dot(a,b.transpose())\n", np.dot(a,b.transpose()))
#they're different dimensons because of dot multiplication again. 
#in dot(a.transpose(),b), a.transpose is 4x6 and multiplied with b which is 6x4 which results in a 4x4 output
#in dot(a,b.transpose()), b.transpose is 6x4 and multiplied with a which is 4x6 which results in a 6x6 output

np.dot(a.transpose(),b)
 [[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]] 

np.dot(a,b.transpose())
 [[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]


## Exercise 5
Write a function that prints some output on the screen and make sure you can run it in the programming environment that you are using.

In [6]:
def printSomething():
    print("something")
    
printSomething();

something


## Exercise 6
Now write one that makes some random arrays and prints out their sums, the mean value, etc.

In [7]:
def makeRandArr():
    arr = np.random.rand(6, 4)
    print(arr)
    print("arr.sum()",arr.sum())
    print("arr.mean()",arr.mean())
    
makeRandArr()

[[0.80095701 0.8840975  0.1237191  0.64132959]
 [0.59273735 0.90337897 0.38474067 0.03870497]
 [0.51660762 0.78020138 0.56101335 0.66692884]
 [0.61134225 0.97777395 0.93225204 0.50398809]
 [0.55766683 0.52507145 0.22658164 0.73199636]
 [0.12978897 0.3290635  0.53759491 0.62339262]]
arr.sum() 13.580928963002851
arr.mean() 0.5658720401251188


## Exercise 7
Write a function that consists of a set of loops that run through an array and count the number of ones in it. Do the same thing using the where() function (use info(where) to find out how to use it).

In [8]:
def countOnes(arr):
    c = 0;
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr[i][j] == 1:
                c += 1
    return c,len(np.where(arr==1)[0])
countOnes(a), countOnes(b)

((0, 0), (20, 20))

## Excercises 8-11
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [9]:
import pandas as pd
import numpy as np
a = pd.DataFrame(np.ones((6,4))*2)
print(a)

     0    1    2    3
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
3  2.0  2.0  2.0  2.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [10]:
b = np.ones((6,4))
b = pd.DataFrame(b)
b.iloc[range(4),range(4)] = 3
print(b)

     0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0


In [11]:
b.values

array([[3., 1., 1., 1.],
       [1., 3., 1., 1.],
       [1., 1., 3., 1.],
       [1., 1., 1., 3.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [12]:
print(a*b)
# np.dot(a, b)

     0    1    2    3
0  6.0  2.0  2.0  2.0
1  2.0  6.0  2.0  2.0
2  2.0  2.0  6.0  2.0
3  2.0  2.0  2.0  6.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [13]:
def countOnes(arr):
    c = 0
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if arr.iloc[i, j] == 1:
                c += 1
    
    return c, len(np.where(arr == 1)[0])
countOnes(a), countOnes(b)

((0, 0), (20, 20))

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [14]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [16]:
titanic_df.index

RangeIndex(start=0, stop=1309, step=1)

In [17]:
df = titanic_df.set_index('sex').loc['female']
df

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

In [19]:
inxs = np.where(titanic_df.survived==1)
inxs
titanic_df.iloc[inxs]

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
5          1         1                              Anderson, Mr. Harry   
6          1         1                Andrews, Miss. Kornelia Theodosia   
8          1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...      ...       ...                                              ...   
1261       3         1                           Turkula, Mrs. (Hedwig)   
1277       3         1                             Vartanian, Mr. David   
1286       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
1290       3         1                 Wilkes, Mrs. James (Ellen Needs)   
1300       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   

         sex      age  sibsp  parch  ticket      fare    cabin embarked  \
0     female  29.0000      0      0   24160  211.3375       B5        S   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   
5       male  48.0000      0      0   19952   26.5500      E12        S   
6     female  63.0000      1      0   13502   77.9583       D7        S   
8     female  53.0000      2      0   11769   51.4792     C101        S   
...      ...      ...    ...    ...     ...       ...      ...      ...   
1261  female  63.0000      0      0    4134    9.5875      NaN        S   
1277    male  22.0000      0      0    2658    7.2250      NaN        C   
1286  female  38.0000      0      0    2688    7.2292      NaN        C   
1290  female  47.0000      1      0  363272    7.0000      NaN        S   
1300  female  15.0000      1      0    2659   14.4542      NaN        C   

       boat  body                        home.dest  
0         2   NaN                     St Louis, MO  
1        11   NaN  Montreal, PQ / Chesterville, ON  
5         3   NaN                     New York, NY  
6        10   NaN                       Hudson, NY  
8         D   NaN              Bayside, Queens, NY  
...     ...   ...                              ...  
1261     15   NaN                              NaN  
1277  13 15   NaN                              NaN  
1286      C   NaN                              NaN  
1290    NaN   NaN                              NaN  
1300    NaN   NaN                              NaN  

[500 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [20]:
titanic_df["name"]

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [29]:
titanic_df.set_index('sex',inplace=True)
titanic_df.loc['female']

level_0  index  pclass  survived  \
sex                                        
female        0      0       1         1   
female        2      2       1         0   
female        4      4       1         0   
female        6      6       1         1   
female        8      8       1         1   
...         ...    ...     ...       ...   
female     1286   1286       3         1   
female     1290   1290       3         1   
female     1300   1300       3         1   
female     1304   1304       3         0   
female     1305   1305       3         0   

                                                   name   age  sibsp  parch  \
sex                                                                           
female                    Allen, Miss. Elisabeth Walton  29.0      0      0   
female                     Allison, Miss. Helen Loraine   2.0      1      2   
female  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0      1      2   
female                Andrews, Miss. Kornelia Theodosia  63.0      1      0   
female    Appleton, Mrs. Edward Dale (Charlotte Lamson)  53.0      2      0   
...                                                 ...   ...    ...    ...   
female  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)  38.0      0      0   
female                 Wilkes, Mrs. James (Ellen Needs)  47.0      1      0   
female          Yasbeck, Mrs. Antoni (Selini Alexander)  15.0      1      0   
female                             Zabour, Miss. Hileni  14.5      1      0   
female                            Zabour, Miss. Thamine   NaN      1      0   

        ticket      fare    cabin embarked boat   body  \
sex                                                      
female   24160  211.3375       B5        S    2    NaN   
female  113781  151.5500  C22 C26        S  NaN    NaN   
female  113781  151.5500  C22 C26        S  NaN    NaN   
female   13502   77.9583       D7        S   10    NaN   
female   11769   51.4792     C101        S    D    NaN   
...        ...       ...      ...      ...  ...    ...   
female    2688    7.2292      NaN        C    C    NaN   
female  363272    7.0000      NaN        S  NaN    NaN   
female    2659   14.4542      NaN        C  NaN    NaN   
female    2665   14.4542      NaN        C  NaN  328.0   
female    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 15 columns]

## Exercise 14
How do you reset the index?

In [30]:
titanic_df.reset_index(inplace=True)
titanic_df

sex  level_0  index  pclass  survived  \
0     female        0      0       1         1   
1       male        1      1       1         1   
2     female        2      2       1         0   
3       male        3      3       1         0   
4     female        4      4       1         0   
...      ...      ...    ...     ...       ...   
1304  female     1304   1304       3         0   
1305  female     1305   1305       3         0   
1306    male     1306   1306       3         0   
1307    male     1307   1307       3         0   
1308    male     1308   1308       3         0   

                                                 name      age  sibsp  parch  \
0                       Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                      Allison, Master. Hudson Trevor   0.9167      1      2   
2                        Allison, Miss. Helen Loraine   2.0000      1      2   
3                Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                               ...      ...    ...    ...   
1304                             Zabour, Miss. Hileni  14.5000      1      0   
1305                            Zabour, Miss. Thamine      NaN      1      0   
1306                        Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                              Zakarian, Mr. Ortin  27.0000      0      0   
1308                               Zimmerman, Mr. Leo  29.0000      0      0   

      ticket      fare    cabin embarked boat   body  \
0      24160  211.3375       B5        S    2    NaN   
1     113781  151.5500  C22 C26        S   11    NaN   
2     113781  151.5500  C22 C26        S  NaN    NaN   
3     113781  151.5500  C22 C26        S  NaN  135.0   
4     113781  151.5500  C22 C26        S  NaN    NaN   
...      ...       ...      ...      ...  ...    ...   
1304    2665   14.4542      NaN        C  NaN  328.0   
1305    2665   14.4542      NaN        C  NaN    NaN   
1306    2656    7.2250      NaN        C  NaN  304.0   
1307    2670    7.2250      NaN        C  NaN    NaN   
1308  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 16 columns]

In [ ]:
## YOUR SOLUTION HERE